spring:
  application:
    name: product-service
  datasource:
    url: ${DB_CONNECTION_URL:jdbc:mysql://localhost:3306/product_service_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Root@123}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: ${PORT:8081}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
springdoc:
  swagger-ui:
    enabled: true
    url: /docs
    path: /swagger-ui.html
  api-docs:
    path: /docs
