spring:
  application:
    name: User-Service
  data:
    mongodb:
      uri: mongodb://localhost:27017/user-service
      database: user-service
      auto-index-creation: true
server:
  port: 8080
#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8765/eureka
#    filter-only-up-instances: true
security:
  jwt:
    secret-key: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"
    expiration-time: 86400000
#grpc:
#  client:
#    hello-service:
#      address: static://localhost:9000
#      negotiationType: PLAINTEXT